"use client"

import Link from "next/link"
import { useState } from "react"
import {
  ArrowLeft,
  Bot,
  XCircle,
  Smartphone,
  Check,
  ShieldCheck,
  CircleCheck,
  Circle,
} from "lucide-react"
import type { Capa, Finding } from "@/lib/data"

const TIMELINE = [
  "Detected",
  "Evidence Assembled",
  "CAPA Drafted",
  "Notified",
  "Approved",
]

export function FindingClient({
  finding,
  capa,
}: {
  finding: Finding
  capa: Capa
}) {
  const [notif, setNotif] = useState<"hidden" | "showing" | "sent">("hidden")

  function sendToQa() {
    if (notif === "showing") return
    setNotif("showing")
    setTimeout(() => setNotif("sent"), 3000)
  }

  return (
    <div className="px-8 py-7 max-w-5xl">
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-slate-800"
      >
        <ArrowLeft className="h-4 w-4" />
        Dashboard
      </Link>

      {/* Top row */}
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <span className="inline-flex items-center rounded-md bg-critical px-2.5 py-1 text-xs font-bold uppercase tracking-wide text-white">
          Critical
        </span>
        <span className="inline-flex items-center rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">
          {finding.regulatory_ref}
        </span>
        <span className="inline-flex items-center rounded-full border border-amber-300 bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">
          CAPA Drafted
        </span>
      </div>

      <h1 className="mt-3 text-xl font-bold tracking-tight">
        Finding #{finding.id} — Temperature Excursion
      </h1>
      <p className="mt-1 text-sm text-slate-500 max-w-3xl">{finding.description}</p>

      {/* Evidence panels */}
      <div className="mt-6 grid gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-slate-200 p-5">
          <h2 className="text-sm font-semibold text-slate-700">Batch Record</h2>
          <dl className="mt-3 space-y-2.5 text-sm">
            <Row label="Batch ID" value={finding.batch_id} mono />
            <Row label="Product" value={finding.product} />
            <div className="flex justify-between">
              <dt className="text-slate-500">Temperature</dt>
              <dd className="font-semibold text-critical tabular-nums">
                {finding.temp_reading.toFixed(1)}°C
              </dd>
            </div>
            <Row label="Spec Range" value={`${finding.spec_min}–${finding.spec_max}°C`} />
            <Row label="Operator" value={finding.operator} mono />
            <Row label="Production Date" value={finding.production_date} />
          </dl>
        </div>

        <div className="rounded-xl border border-slate-200 p-5">
          <h2 className="text-sm font-semibold text-slate-700">eQMS Status</h2>
          <div className="mt-4 flex flex-col items-center justify-center rounded-lg bg-red-50 py-6 text-center">
            <XCircle className="h-10 w-10 text-critical" />
            <div className="mt-2 text-base font-bold text-critical">
              No Deviation Report Filed
            </div>
            <div className="mt-1 text-xs font-medium text-critical/80">
              Gap detected across systems
            </div>
          </div>
          <p className="mt-3 text-xs text-slate-500">
            AuditAI cross-referenced eQMS — filing absent
          </p>
        </div>
      </div>

      {/* CAPA Draft */}
      <div className="mt-6 rounded-xl border border-slate-200 border-l-4 border-l-blue-500 bg-blue-50/40 p-5">
        <div className="flex items-center gap-2">
          <span className="flex h-7 w-7 items-center justify-center rounded-md bg-blue-600">
            <Bot className="h-4 w-4 text-white" />
          </span>
          <div>
            <h2 className="text-sm font-bold text-slate-800">
              CAPA Draft — Generated by AuditAI
            </h2>
            <p className="text-xs text-slate-500">Awaiting human approval</p>
          </div>
        </div>

        <div className="mt-4 space-y-4 text-sm">
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Root Cause
            </div>
            <p className="mt-1 text-slate-700">{capa.root_cause}</p>
          </div>
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Corrective Action
            </div>
            <p className="mt-1 text-slate-700">{capa.corrective_action}</p>
          </div>
          <span className="inline-flex items-center rounded-md bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">
            {capa.regulatory_ref}
          </span>
        </div>
      </div>

      {/* Send to QA */}
      <div className="mt-5 flex items-center gap-4">
        <Link
          href={`/capa/${finding.id}/approve`}
          onClick={sendToQa}
          className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800"
        >
          <Smartphone className="h-4 w-4" />
          Send to QA Manager for Approval
        </Link>
        {notif === "sent" && (
          <span className="inline-flex items-center gap-1.5 text-sm font-medium text-compliant">
            <Check className="h-4 w-4" />
            Notification sent to Sarah Chen
          </span>
        )}
      </div>

      {/* Timeline */}
      <div className="mt-8">
        <h2 className="text-sm font-semibold text-slate-700 mb-4">Status Timeline</h2>
        <ol className="flex flex-wrap items-center gap-x-2 gap-y-3">
          {TIMELINE.map((step, i) => {
            const complete = i < 4
            return (
              <li key={step} className="flex items-center gap-2">
                <div className="flex items-center gap-1.5">
                  {complete ? (
                    <CircleCheck className="h-5 w-5 text-compliant" />
                  ) : (
                    <Circle className="h-5 w-5 text-slate-300" />
                  )}
                  <span
                    className={`text-xs font-medium ${
                      complete ? "text-slate-700" : "text-slate-400"
                    }`}
                  >
                    {step}
                  </span>
                </div>
                {i < TIMELINE.length - 1 && (
                  <span className="h-px w-6 bg-slate-200" />
                )}
              </li>
            )
          })}
        </ol>
      </div>

      {/* Mock iPhone notification overlay */}
      {notif === "showing" && (
        <div className="fixed right-6 top-6 z-50 slide-in-right">
          <div className="w-80 rounded-2xl bg-white/90 p-4 shadow-2xl ring-1 ring-black/5 backdrop-blur">
            <div className="flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600">
                <ShieldCheck className="h-4 w-4 text-white" />
              </span>
              <span className="text-xs font-semibold text-slate-500">AuditAI</span>
              <span className="ml-auto text-[10px] text-slate-400">now</span>
            </div>
            <div className="mt-2">
              <div className="text-sm font-bold text-slate-900">CAPA Approval Required</div>
              <div className="text-xs text-slate-600 mt-0.5">
                BCH-2024-0892 — Critical finding awaiting your review
              </div>
            </div>
            <div className="mt-3 flex gap-2">
              <button className="flex-1 rounded-lg bg-compliant py-2 text-xs font-semibold text-white">
                Approve
              </button>
              <button className="flex-1 rounded-lg bg-slate-100 py-2 text-xs font-semibold text-slate-600">
                Review
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function Row({
  label,
  value,
  mono,
}: {
  label: string
  value: string
  mono?: boolean
}) {
  return (
    <div className="flex justify-between">
      <dt className="text-slate-500">{label}</dt>
      <dd className={`font-medium text-slate-800 ${mono ? "font-mono text-xs" : ""}`}>
        {value}
      </dd>
    </div>
  )
}
